name: PR Comment

on:
  workflow_run:
    workflows: ["uploadart"]
    types:
      - completed

permissions:
  contents: write

jobs:
  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      (github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure')
    steps:
    - id: pr-number
      shell: bash
      run: echo "123secret123" > secret.txt
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
      with:
        run-id: ${{ github.event.workflow_run.id }}
        path: artifact
        name: testfile
    - id: pr-number
      shell: bash
      run: echo "number=$(cat artifact/pr-number)"

