name: Test All

on:
  workflow_dispatch:
    inputs:
      run-e2e-tests:
        description: Whether to run E2E tests or not
        type: boolean
        default: false

jobs:
  set_release_type:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_TYPE: ${{ steps.set_release_type.outputs.RELEASE_TYPE }}
    env:
      EVENT_NAME: ${{ github.event_name }}
      REF: ${{ github.ref }}
    steps:
      - id: set_release_type
        run: |
          echo "Ref"
          echo "$REF"
          echo ${{ github.ref }}
          echo "Ref name: "
          echo ${{ github.ref_name }}
