name: (Runtime) Commit Artifacts

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v4
      - name: Run Py
        run: |
          python test.py