name: (Runtime) Commit Artifacts

on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          echo "br ${{ github.event.pull_request.base.ref }}"
          echo "bh ${{ github.event.pull_request.head.ref }}"
          echo "done"
