name: (Runtime) Commit Artifacts

on:
  workflow_run:
    workflows: ["(Runtime) Build and Test"]
    types: [completed]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          echo "$HOME"
          pwd
          echo ${{ toJSON( github.event ) }}