name: WF-Download

on:
  workflow_run:
    workflows: ["UploadArt"]
    types:
      - completed

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions DL
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: LS
        run: |
          echo "Artifacts dir:"
          ls -la artifacts/
          echo "Current directory."
          ls -la .
