name: BooFarWFRun

on:
  workflow_run:
    workflows: ["A"]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions DL
        uses: actions/download-artifact@v4
      - name: LS
        run: |
          ls -la .
          echo "Parent dir."
          ls -la ..
