name: BooFarWFRun

on:
  workflow_run:
    workflows: ["UploadArt"]
    types:
      - completed

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions DL
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: LS
        run: |
          ls -la .
          echo "Parent dir."
          ls -la ..
